# Generated by Django 5.2 on 2025-04-11 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0003_empleado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=10)),
                ("descripcion", models.TextField()),
                (
                    "precio_noche",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tipo", models.CharField(max_length=50)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("ocupada", "Ocupada"),
                            ("mantenimiento", "Mantenimiento"),
                        ],
                        default="disponible",
                        max_length=50,
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        limit_choices_to={"rol": "hotel"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReporteContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                ("archivo_excel", models.FileField(upload_to="reportes/")),
                (
                    "generado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.empleado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_reserva", models.DateTimeField(auto_now_add=True)),
                ("fecha_checkin", models.DateField()),
                ("fecha_checkout", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmada", "Confirmada"),
                            ("cancelada", "Cancelada"),
                            ("finalizada", "Finalizada"),
                        ],
                        default="pendiente",
                        max_length=50,
                    ),
                ),
                ("metodo_pago", models.CharField(max_length=50)),
                (
                    "monto_total",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas_gestionadas",
                        to="profiles.empleado",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        limit_choices_to={"rol": "hotel"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"rol": "usuario"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas_cliente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComprobantePago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo_comprobante",
                    models.FileField(upload_to="comprobantes/"),
                ),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "reserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comprobantes",
                        to="reserves.reserva",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservaHabitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "habitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reserves.habitacion",
                    ),
                ),
                (
                    "reserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reserves.reserva",
                    ),
                ),
            ],
        ),
    ]
