# Generated by Django 5.2 on 2025-04-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserves", "0002_reserva_correo_reserva_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="correo",
            field=models.EmailField(default="hotelera.com@gmail.com", max_length=254),
        ),
    ]
