# Generated by Django 5.2 on 2025-04-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AddField(
            model_name="user",
            name="direccion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nombre_completo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nombre_hotel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="numero_cedula",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="rol",
            field=models.CharField(
                choices=[
                    ("usuario", "Usuario Particular"),
                    ("hotel", "Hotel"),
                ],
                default="usuario",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telefono",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
