# Generated by Django 5.2 on 2025-04-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_empleado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="numero_cedula",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Número de cédula",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="rol",
            field=models.CharField(
                choices=[
                    ("usuario", "Usuario Particular"),
                    ("hotel", "Hotel"),
                    ("empleado", "Empleado"),
                ],
                default="usuario",
                max_length=10,
            ),
        ),
    ]
