# Generated by Django 5.2 on 2025-04-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_user_numero_cedula_alter_user_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="imagen_hotel",
            field=models.ImageField(
                blank=True, null=True, upload_to="hotel_images/"
            ),
        ),
    ]
